project_id = "avian-direction-235610"
region = "us-central1"
master_user_name = "rpcuser"
master_user_password = "rpcpassword@1"
instance_name = "bitcoin-por-indexer-db"
db_name = "bitcoin-por-indexer-db"
#machine_type = "db-custom-2-13312"
machine_type = "db-custom-8-53248"